# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

WORKDIR /app

# Copy the repository into the container
COPY . .

# Upgrade pip and install the package
RUN pip install --upgrade pip \
    && pip install .

# Expose port if necessary (not required by MCP, but placeholder)
# EXPOSE 8000

# Command to start the MCP server
CMD ["mcp-multilspy"]
